language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo -s tools/travis_update_packages

script:
  - cmake -DWITH_QSTAT=/usr/bin/quakestat -DCMAKE_C_FLAGS=-Werror .
  - make

notifications:
  irc: "chat.freenode.net#xqf"
  on_success: change
  on_failure: always
